### ISSUE TITLE
Firefox repeatedly asks for updating login information

### ISSUE THREAD

**Issue by davelit** [smorks/passifox#3]
Original issue is here: [#649](https://github.com/pfn/passifox/issues/649). I see the same on my end.

**Comment by smorks** [comment]
does this happen on all websites, or just some? if just some, can you give me some examples?

i tried on a few different sites and couldn't reproduce the problem.

**Comment by davelit** [comment]
Yes, it happens on all websites, even on GitHub. I have my credentials in my KeePass already and chromeIPass filled the login fields with them, but still wants to save them again after submitting the form.

Here is what I get with a new install of Firefox 55.0.4 64 bit on Windows 7 64 bit, with just your recent chromeIPass 2.8.5 release installed and nothing else:

![image](https://user-images.githubusercontent.com/31506161/29947207-bea74bba-8ea8-11e7-9340-11f5fa72f28e.png)

![image](https://user-images.githubusercontent.com/31506161/29947350-6d18f7a2-8ea9-11e7-947b-d7bdea605230.png)

**Comment by smorks** [comment]
That is firefox's built in password manager. You just need to switch it off in Options -> Security -> Remember logins for sites.

I think the "legacy" version of passifox somehow used it, but this new version is completely independent of it.

**Comment by davelit** [comment]
But what if I register to a new site? The old Passifox used to allow me to add newly created credentials to KeePass using Firefox's built in password manager dialog.

**Comment by smorks** [comment]
there's no way (that i'm aware of) to tie in to the built in password manager like the old passifox used to do, because of limitations in the WebExtensions API.

**Comment by davelit** [comment]
Got it, there's nothing that can be done here then.
