### ISSUE TITLE
Plugin popup shows credentials from previous login on other domains

### ISSUE THREAD

**Issue by davelit** [smorks/passifox#4]
If I move to another site, visit their login page and then click into the fields for the login forms, nothing happens (which is fine), however, the chromeIPass icon in the browser toolbar shows a little red dot indicating that there is something for me to look at. Once open, the plugin dropdown gives me the list of credentials from the last site I _visited_ for which I have credentials in KeePass (even if I didn't actually log in).

Version: chromeIPass 2.8.5

How to reproduce:
1) Browse to a site for which you have credentials stored
2) Browse to anothe site, for which you do _not_ have credentials stored
3) Click on the chromeIPass icon

Screenshot:

![grafik](https://user-images.githubusercontent.com/31506161/29947957-8465b83e-8eac-11e7-936b-fe75aa4ac77f.png)

**Comment by smorks** [comment]
this appears to happen in 2.8.4 too, so at least i didn't break something in the latest update. i'll look into it.
