### ISSUE TITLE
please give  a donate  link

### ISSUE THREAD

**Issue by ydf** [smorks/passifox#5]
thank u hard work , I am a firefox user.

**Comment by smorks** [comment]
@projectgus did most of the hard work, i've just added on a few things, so i don't feel comfortable taking money for that.

**Comment by projectgus** [comment]
Eh, I didn't do that much - most of the work is in the original chromeipass tbh. But if adding a donate link makes the project more sustainable for you then don't avoid it on my behalf.

**Comment by smorks** [comment]
I'm just happy people are finding it useful. I'm really just not comfortable taking money for it currently. thanks for the offer though @ydf.
