### ISSUE TITLE
Not detecting KeePassHttp on Waterfox

### ISSUE THREAD

**Issue by Aanok** [smorks/passifox#6]
On Waterfox 55.0.2, the extension doesn't detect KeePassHttp.
It does so on Firefox 55.0.3, however, and then works perfectly fine.
I am running KeePassXC 2.2.0.

**Comment by smorks** [comment]
i just tested with Waterfox 55.0.2 & KeePassXC 2.2.0, and once i enabled the KeePassHTTP Server option everything worked fine.

Also, what OS are you running?

**Comment by Aanok** [comment]
Arch Linux.

**Comment by smorks** [comment]
i did a quick test in Arch Linux, everything worked fine for me.

are you using any sort of proxy/vpn extensions? those may cause issues, try with them disabled?

![virtualbox_arch_01_09_2017_10_11_21](https://user-images.githubusercontent.com/1030007/29976475-c40f970e-8eff-11e7-929c-e9427dbcd9d8.png)

**Comment by Aanok** [comment]
Oh dear, this is embarrassing. Not VPN, turns out uMatrix (which I did not have installed on Firefox) was blocking XHR's to localhost. Allowed them, now everything works nicely.

Sorry, should have thought about extensions before. Thanks for the help!
