### ISSUE TITLE
Database dates are not stored with Chrome/Chromium

### ISSUE THREAD

**Issue by varjolintu** [smorks/passifox#7]
After changing the localStorage handling to browser.storage.local the Date() objects are not saved correctly with Chrome/Chromium. The Settings -> Connected Databases page always shows  "Invalid date" instead of a correct date. Debugging the saving and loading of the keyring you can clearly see the Date objects exists but when the keyring is loaded those objects are empty.

When inspecting the issue it seems that you can only save strings to localStorage, where Date()'s are objects. The old implementation used JSON for the whole localStorage.

While Firefox can handle this issue but for some reason Chrome/Chromium doesn't.

Possible olution:
- Add JSON.parse() and JSON.stringify() to localStorages keyRing handling

**Comment by smorks** [comment]
i found this: https://bugs.chromium.org/p/chromium/issues/detail?id=161319

anyways, it shouldn't be too hard to work around. i should have this fixed when i have some time in the next few days.
